version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: personal-website-.docker
    ports:
      - 80:80
      - 8080:80
    volumes:
      - .:/srv/app
    links:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: personal_website
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password